services:
  writefreely-vijay:
    build:
      context: .
#    restart: unless-stopped
    ports:
      - $PORT:8080
    environment:
      - USERNAME
      - PASSWORD
    volumes:
      - ./config:/config:Z
      - ./data:/data:Z
